### ISSUE TITLE
错字及翻译问题

### ISSUE THREAD

**Issue by uoay** [CakeAL/mini-redis-tokio-tutorial-zh#2]
async in depth章节，“异步函数作为 Future”部分，第一行“我们示例化了 future”，示例化->实例化。还是这一栏，倒数第四行，“尝试推进其他内部状态”，原文为“the future attempts to advance its internal state as much as possible”，应该是多了一个“他”。

同一章节，”唤醒者 Wakers“部分，开篇“这是当一个资源能够通知正在等待中的任务资源已就绪，可以继续操作的系统”有些难以理解，原文为“This is the system by which a resource is able to notify the waiting task that the resource has become ready to continue some operation.”，我认为翻译为“这是一个使资源可以在准备好继续某些操作时通知正在等待的任务的系统”会更好一些。

同一章节，总结部分，倒数第二行，”通道“->”通知”。

**Comment by CakeAL** [comment]
https://github.com/CakeAL/mini-redis-tokio-tutorial-zh/commit/e9733544b4694ca1705938aa3136dd9d3bee4e2e 
已改
