### ISSUE TITLE
建议用 vitepress 来管理项目

### ISSUE THREAD

**Issue by liaohui5** [CakeAL/mini-redis-tokio-tutorial-zh#3]
建议用 [vitepress](https://vitepress.dev/zh/) 来管理文档, vitepress 非常简单易学

1. 美化样式, 现在的样式不利于阅读(目录不在左侧)
2. 可以利用 Github Actions [直接一键部署](https://vitepress.dev/zh/guide/deploy#github-pages)

**Comment by CakeAL** [comment]
https://github.com/CakeAL/mini-redis-tokio-tutorial-zh/commit/e9733544b4694ca1705938aa3136dd9d3bee4e2e
使用了 mdbook，因为懒
